import turtle
loka=turtle.Turtle()
loka.pencolor("red")
loka.pensize(90)
loka.circle(100)
loka.pencolor("blue")
loka.pensize(70)
loka.circle(100)
loka.pencolor("yellow")
loka.pensize(40)
loka.circle(100)
loka.pencolor("green")
loka.pensize(10)
loka.circle(100)
input("press enter to exit...")