import turtle
zizi=turtle.Turtle()
zizi.pencolor("black")
zizi.pensize(20)
zizi.circle(100)
zizi.pencolor("blue")
zizi.pensize(20)
zizi.circle(90)
zizi.pencolor("red")
zizi.pensize(20)
zizi.circle(80)
zizi.pencolor("yellow")
zizi.pensize(20)
zizi.circle(70)
input("press enter to exit...")