import turtle
ahmed=turtle.Turtle()
ahmed.pencolor("red")
ahmed.pensize(10)
ahmed.circle(100)
ahmed.left(90)
ahmed.pencolor("blue")
ahmed.pensize(10)
ahmed.circle(100)
ahmed.left(90)
ahmed.pencolor("green")
ahmed.pensize(10)
ahmed.circle(100)
ahmed.left(90)
ahmed.pencolor("yellow")
ahmed.pensize(10)
ahmed.circle(100)
ahmed.left(90)
input("press enter to exit...")
